name = "cca-f-apoyo"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "cca-f-db"
database_id = "REPLACE_WITH_DATABASE_ID_FROM_WRANGLER_D1_CREATE"
